function shuffleGallery(){const gallery=document.querySelector('.gallery');if(!gallery)return;if(document.body.classList.contains('experiments-page'))return;const items=Array.from(gallery.children);for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}
gallery.innerHTML='';items.forEach(item=>gallery.appendChild(item));gallery.querySelectorAll('video').forEach((v)=>{v.play().catch(()=>{});});}
function makeZinCursorUrl(current,total){const text=`${current}/${total}`;const svg=`<svg xmlns="http://www.w3.org/2000/svg"width="110"height="40"><text x="0"y="32"font-size="32"fill="#FB0000"font-family="Alegreya, serif">${text}</text></svg>`;const encoded=encodeURIComponent(svg).replace(/#/g,'%23');return`url("data:image/svg+xml,${encoded}")0 0,pointer`;}
function zinGallerySwipeSide(viewport,clientX){if(!viewport)return'next';const rect=viewport.getBoundingClientRect();if(rect.width<=0)return'next';return clientX-rect.left<rect.width/2?'prev':'next';}
function makeZinSwipeHintCursorUrl(current,total,side){const text=`${current}/${total}`;const svg=`<svg xmlns="http://www.w3.org/2000/svg"width="90"height="40"><text x="0"y="32"font-size="32"fill="#FB0000"font-family="Alegreya, serif">${text}</text></svg>`;const encoded=encodeURIComponent(svg).replace(/#/g,'%23');return`url("data:image/svg+xml,${encoded}")0 0,pointer`;}
function makeZinSwipeHintCursorUrlNoCount(side){if(side==='prev')return`url("img/Back_r.svg") 4 7, pointer`;return`url("img/Next_r.svg") 3 7, pointer`;}
function zinGallerySlideImg(slide){if(!slide)return null;return slide.tagName==='IMG'?slide:slide.querySelector('img');}
function isPillarCaseGallery(gallery){const img=zinGallerySlideImg(gallery.querySelector('.zin-gallery-slide'));if(!img)return false;const raw=img.getAttribute('src')||'';const file=raw.split('?')[0].split('/').pop()||'';return/^pillar\d+\.webp$/i.test(file);}
function prunePillarGallery(gallery){if(!isPillarCaseGallery(gallery))return Promise.resolve();const track=gallery.querySelector('.zin-gallery-track');if(!track)return Promise.resolve();const slides=Array.from(gallery.querySelectorAll('.zin-gallery-slide'));const PILLAR_PRUNE_MS=8000;const promises=slides.map((slide,slideIndex)=>{const img=zinGallerySlideImg(slide);if(!img)return Promise.resolve();if(slideIndex===0)return Promise.resolve();return new Promise((resolve)=>{let settled=false;let timer;const finish=(loaded)=>{if(settled)return;settled=true;clearTimeout(timer);resolve(loaded);};timer=setTimeout(()=>finish(true),PILLAR_PRUNE_MS);img.onload=()=>finish(img.naturalWidth>0);img.onerror=()=>finish(false);if(img.complete){finish(img.naturalWidth>0);}}).then((loaded)=>{if(!loaded)slide.remove();});});return Promise.all(promises);}
function prunePillarGalleries(){const galleries=document.querySelectorAll('.zin-gallery');return Promise.all(Array.from(galleries).map(prunePillarGallery));}
const zinGalleryKeyNavApi=new WeakMap();let zinGalleryKeyNavListenerAttached=false;var syncGalleryCustomCursor=null;var galleryHoverZinEl=null;function zinGalleryVisibilityRatio(el){const r=el.getBoundingClientRect();const vw=window.innerWidth;const vh=window.innerHeight;const w=Math.max(0,Math.min(r.right,vw)-Math.max(0,r.left));const h=Math.max(0,Math.min(r.bottom,vh)-Math.max(0,r.top));const area=r.width*r.height;if(area<=0)return 0;return(w*h)/area;}
function getActiveZinGalleryForKeyboard(){let best=null;let bestRatio=0;document.querySelectorAll('.zin-gallery').forEach((g)=>{if(!zinGalleryKeyNavApi.has(g))return;const ratio=zinGalleryVisibilityRatio(g);if(ratio>bestRatio){bestRatio=ratio;best=g;}});if(bestRatio<0.12)return null;return best;}
function onZinGalleryDocumentKeydown(e){if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;const t=e.target;if(t&&(t.closest&&t.closest('input, textarea, select, [contenteditable="true"]')))return;const gallery=getActiveZinGalleryForKeyboard();if(!gallery)return;const api=zinGalleryKeyNavApi.get(gallery);if(!api)return;e.preventDefault();if(e.key==='ArrowRight')api.next();else api.prev();}
function attachZinGalleryKeyboardNav(galleryEl,api){zinGalleryKeyNavApi.set(galleryEl,api);if(zinGalleryKeyNavListenerAttached)return;zinGalleryKeyNavListenerAttached=true;document.addEventListener('keydown',onZinGalleryDocumentKeydown);}
function initOneZinGallery(gallery){const track=gallery.querySelector('.zin-gallery-track');const viewport=gallery.querySelector('.zin-gallery-viewport');const slides=gallery.querySelectorAll('.zin-gallery-slide');const total=slides.length;if(!track||total===0)return;const wrap=gallery.closest('.zin-gallery-wrap');const isZineWrap=wrap?.classList.contains('zin-gallery-wrap--zine');const hideGalleryPhotoCount=document.body.classList.contains('graphics-3d-case-page');const thumbsContainer=wrap?wrap.querySelector('.zin-gallery-thumbs'):null;let thumbs=wrap?wrap.querySelectorAll('.zin-gallery-thumb'):[];Array.from(thumbs).forEach((t)=>{const i=parseInt(t.dataset.index,10);if(!isNaN(i)&&i>=total)t.remove();});thumbs=wrap?wrap.querySelectorAll('.zin-gallery-thumb'):[];if(total===5)gallery.classList.add('zin-gallery--5');if(total===6)gallery.classList.add('zin-gallery--6');if(total===7)gallery.classList.add('zin-gallery--7');if(total===10)gallery.classList.add('zin-gallery--10');let index=0;let hoverSide='next';function updateCursor(){if(isZineWrap&&viewport){gallery.style.cursor=hideGalleryPhotoCount?makeZinSwipeHintCursorUrlNoCount(hoverSide):makeZinSwipeHintCursorUrl(index+1,total,hoverSide);}else{gallery.style.cursor=hideGalleryPhotoCount?'none':makeZinCursorUrl(index+1,total);}}
function updateThumbs(){thumbs.forEach((t,j)=>t.classList.toggle('is-selected',j===index));}
function scrollThumbIntoView(){if(!thumbsContainer||!thumbs[index])return;const thumb=thumbs[index];const scrollLeft=thumbsContainer.scrollLeft;const thumbLeft=thumb.offsetLeft;const thumbRight=thumbLeft+thumb.offsetWidth;const visibleLeft=scrollLeft;const visibleRight=scrollLeft+thumbsContainer.clientWidth;const isVisible=thumbLeft>=visibleLeft&&thumbRight<=visibleRight;if(isVisible)return;const targetScroll=thumb.offsetLeft-101;const maxScroll=thumbsContainer.scrollWidth-thumbsContainer.clientWidth;thumbsContainer.scrollTo({left:Math.max(0,Math.min(targetScroll,maxScroll)),behavior:'smooth'});}
function goTo(i){index=((i%total)+total)%total;track.style.transform=`translateX(-${(index/total)*100}%)`;gallery.dataset.currentIndex=String(index+1);gallery.dataset.total=String(total);updateCursor();updateThumbs();scrollThumbIntoView();const customCursor=document.getElementById('custom-cursor');if(customCursor?.classList.contains('custom-cursor--gallery')&&galleryHoverZinEl===gallery&&typeof syncGalleryCustomCursor==='function'){const x=parseInt(customCursor.style.left,10)||0;const y=parseInt(customCursor.style.top,10)||0;syncGalleryCustomCursor(gallery,x,y);}}
gallery.dataset.total=String(total);gallery.dataset.currentIndex='1';function next(){goTo(index+1);}
thumbs.forEach((thumb)=>{const i=parseInt(thumb.dataset.index,10);if(isNaN(i))return;thumb.addEventListener('click',()=>{goTo(i);});});if(wrap?.classList.contains('zin-gallery-wrap--zine')){wrap.addEventListener('dragstart',(e)=>e.preventDefault(),true);}
gallery.addEventListener('mouseenter',updateCursor);if(isZineWrap&&viewport){gallery.addEventListener('mousemove',(e)=>{const s=zinGallerySwipeSide(viewport,e.clientX);if(s!==hoverSide){hoverSide=s;updateCursor();}if(typeof syncGalleryCustomCursor==='function'){const c=document.getElementById('custom-cursor');if(c?.classList.contains('custom-cursor--gallery'))syncGalleryCustomCursor(gallery,e.clientX,e.clientY);}},{passive:true});}
gallery.addEventListener('click',(e)=>{const isZineCase=wrap?.classList.contains('zin-gallery-wrap--zine');if(isZineCase&&viewport){const rect=viewport.getBoundingClientRect();if(rect.width>0){const relX=e.clientX-rect.left;if(relX<rect.width/2)goTo(index-1);else next();return;}}
next();});let touchStartX=0;let touchEndX=0;gallery.addEventListener('touchstart',(e)=>{touchStartX=e.changedTouches[0].screenX;},{passive:true});gallery.addEventListener('touchend',(e)=>{touchEndX=e.changedTouches[0].screenX;const diff=touchStartX-touchEndX;const minSwipe=50;if(diff>minSwipe)next();else if(diff<-minSwipe)goTo(index-1);},{passive:true});attachZinGalleryKeyboardNav(gallery,{next:()=>goTo(index+1),prev:()=>goTo(index-1)});updateCursor();updateThumbs();}
function initZinGallery(){document.querySelectorAll('.zin-gallery').forEach(initOneZinGallery);}
function initOneZinGalleryMobileReveal(wrap){const gallery=wrap.querySelector('.zin-gallery');const total=gallery?gallery.querySelectorAll('.zin-gallery-slide').length:0;if(!gallery||!total)return;const isMobile=()=>window.matchMedia('(max-width: 768px)').matches;if(!isMobile()){wrap.classList.add('gallery-loaded');return;}
let done=false;const observer=new IntersectionObserver((entries)=>{if(done)return;const entry=entries[0];if(!entry.isIntersecting)return;done=true;observer.disconnect();wrap.classList.add('gallery-loaded');},{rootMargin:'0px',threshold:0.2});observer.observe(wrap);}
function initZinGalleryMobileReveal(){document.querySelectorAll('.zin-gallery-wrap').forEach(initOneZinGalleryMobileReveal);}
function initCustomCursor(){if(!window.matchMedia('(hover: hover)').matches)return;let cursor=document.getElementById('custom-cursor');if(!cursor){cursor=document.createElement('div');cursor.className='custom-cursor';cursor.id='custom-cursor';cursor.innerHTML='<img class="custom-cursor-main" src="img/cursor.svg" alt="" width="48" height="48"><img class="custom-cursor-gallery-arrow" alt="" width="16" height="32" aria-hidden="true"><span class="custom-cursor-gallery-count" aria-hidden="true"></span>';document.body.appendChild(cursor);document.body.classList.add('has-custom-cursor');document.documentElement.classList.add('has-custom-cursor');}else{const mainIm=cursor.querySelector('img.custom-cursor-main')||cursor.querySelector('img');if(mainIm&&!mainIm.classList.contains('custom-cursor-main'))mainIm.classList.add('custom-cursor-main');if(!cursor.querySelector('.custom-cursor-gallery-arrow')){const im=cursor.querySelector('img.custom-cursor-main')||cursor.querySelector('img');if(im)im.insertAdjacentHTML('afterend','<img class="custom-cursor-gallery-arrow" alt="" width="16" height="32" aria-hidden="true">');else cursor.insertAdjacentHTML('afterbegin','<img class="custom-cursor-gallery-arrow" alt="" width="16" height="32" aria-hidden="true">');}if(!cursor.querySelector('.custom-cursor-gallery-count')){cursor.insertAdjacentHTML('beforeend','<span class="custom-cursor-gallery-count" aria-hidden="true"></span>');}}const legacyGalleryArrow=cursor.querySelector('span.custom-cursor-gallery-arrow');if(legacyGalleryArrow){const na=document.createElement('img');na.className='custom-cursor-gallery-arrow';na.setAttribute('width','16');na.setAttribute('height','32');na.alt='';na.setAttribute('aria-hidden','true');legacyGalleryArrow.replaceWith(na);}
var savedX=sessionStorage.getItem('cursorX');var savedY=sessionStorage.getItem('cursorY');if(savedX!==null&&savedY!==null){cursor.style.left=savedX+'px';cursor.style.top=savedY+'px';}
let x=savedX!==null?Number(savedX):0;let y=savedY!==null?Number(savedY):0;let lastPointerX=x;let lastPointerY=y;function move(e){x=e.clientX;y=e.clientY;lastPointerX=x;lastPointerY=y;cursor.style.left=x+'px';cursor.style.top=y+'px';sessionStorage.setItem('cursorX',String(x));sessionStorage.setItem('cursorY',String(y));if(cursor.classList.contains('custom-cursor--gallery')&&galleryHoverZinEl)applyGalleryCursorVisual(galleryHoverZinEl,x,y);}
function press(){cursor.classList.add('custom-cursor--pressed');}
function release(){cursor.classList.remove('custom-cursor--pressed');}
document.addEventListener('mousemove',move,{passive:true});document.addEventListener('mousedown',press);document.addEventListener('mouseup',release);document.addEventListener('mouseleave',release);const countEl=cursor.querySelector('.custom-cursor-gallery-count');const arrowEl=cursor.querySelector('.custom-cursor-gallery-arrow');function applyGalleryCursorVisual(galleryEl,clientX,clientY){if(!countEl||!galleryEl)return;if(document.body.classList.contains('graphics-3d-case-page')){countEl.textContent='';}else{const cur=galleryEl.dataset.currentIndex||'1';const tot=galleryEl.dataset.total||'1';countEl.textContent=cur+'/'+tot;}const wrap=galleryEl.closest('.zin-gallery-wrap');const isZine=wrap?.classList.contains('zin-gallery-wrap--zine');const viewport=galleryEl.querySelector('.zin-gallery-viewport');const cx=Number.isFinite(clientX)?clientX:lastPointerX;if(isZine&&viewport){cursor.classList.add('custom-cursor--gallery-zine');if(arrowEl){const swipe=zinGallerySwipeSide(viewport,cx);arrowEl.src=swipe==='prev'?'img/Back_r.svg':'img/Next_r.svg';}}else{cursor.classList.remove('custom-cursor--gallery-zine');if(arrowEl)arrowEl.removeAttribute('src');}}
syncGalleryCustomCursor=applyGalleryCursorVisual;function updateGalleryCursor(galleryEl,cx,cy){const px=Number.isFinite(cx)?cx:lastPointerX;const py=Number.isFinite(cy)?cy:lastPointerY;applyGalleryCursorVisual(galleryEl,px,py);}
document.querySelectorAll('.zin-gallery').forEach((el)=>{el.addEventListener('mouseenter',(e)=>{cursor.classList.remove('custom-cursor--hidden');cursor.classList.add('custom-cursor--gallery');galleryHoverZinEl=el;updateGalleryCursor(el,e.clientX,e.clientY);});el.addEventListener('mouseleave',()=>{galleryHoverZinEl=null;cursor.classList.remove('custom-cursor--gallery');cursor.classList.remove('custom-cursor--gallery-zine');if(arrowEl)arrowEl.removeAttribute('src');});});}
const SPLASH_CURSOR_SRC='img/cursor3.webp';function splashCursorGraphicEl(){const cur=document.getElementById('custom-cursor');if(!cur)return null;return cur.querySelector('img.custom-cursor-main')||cur.querySelector('img:first-of-type');}
function applySplashCursorGraphic(){if(!document.getElementById('splash'))return;const im=splashCursorGraphicEl();if(!im)return;if(!im.dataset.preSplashCursorSrc){im.dataset.preSplashCursorSrc=im.getAttribute('src')||'img/cursor.svg';}
im.src=SPLASH_CURSOR_SRC;}
function restoreSplashCursorGraphic(){const im=splashCursorGraphicEl();if(!im||!im.dataset.preSplashCursorSrc)return;im.src=im.dataset.preSplashCursorSrc;delete im.dataset.preSplashCursorSrc;}
function initSplash(){if(sessionStorage.getItem('splash-seen'))return;const splash=document.createElement('div');splash.className='splash';splash.id='splash';splash.innerHTML='<div class="splash-inner">'+
'<div class="splash-img-wrap">'+
'<img src="img/rock.webp" alt="" class="splash-img" loading="eager">'+
'<canvas class="splash-canvas" aria-hidden="true"></canvas>'+
'<img src="img/Mask.webp" alt="" class="splash-mask" aria-hidden="true" loading="eager">'+
'</div>'+
'<p class="splash-text">Clear the area</p>'+
'</div>';document.body.prepend(splash);const wrap=splash.querySelector('.splash-img-wrap');const img=splash.querySelector('.splash-img');const maskEl=splash.querySelector('.splash-mask');const canvas=splash.querySelector('.splash-canvas');const textEl=splash.querySelector('.splash-text');let ctx=null;let revealed=false;let drawing=false;let lastX;let lastY;let rafCheck=null;const REVEAL_THRESHOLD=0.74;const BRUSH=76;const SPLASH_TILT_MAX=11;let splashTiltBound=false;function bindSplashReadyHoverTilt(){if(splashTiltBound||!wrap)return;if(!window.matchMedia('(hover: hover)').matches)return;splashTiltBound=true;function onWrapMove(e){if(!splash.classList.contains('splash--ready'))return;const r=wrap.getBoundingClientRect();const mx=((e.clientX-r.left)/r.width)*2-1;const my=((e.clientY-r.top)/r.height)*2-1;const px=Math.max(-1,Math.min(1,mx));const py=Math.max(-1,Math.min(1,my));const rotY=px*SPLASH_TILT_MAX;const rotX=-py*SPLASH_TILT_MAX;const t=`rotateX(${rotX}deg) rotateY(${rotY}deg) scale3d(1.04,1.04,1)`;wrap.style.webkitTransform=t;wrap.style.transform=t;}
function onWrapEnter(){if(!splash.classList.contains('splash--ready'))return;wrap.classList.add('splash-img-wrap--tilt-live');}
function onWrapLeave(){wrap.classList.remove('splash-img-wrap--tilt-live');wrap.style.webkitTransform='';wrap.style.transform='';}
wrap.addEventListener('mouseenter',onWrapEnter);wrap.addEventListener('mousemove',onWrapMove);wrap.addEventListener('mouseleave',onWrapLeave);}
function isMainPage(){const p=window.location.pathname;return p===''||p==='/'||p.endsWith('/')||p.endsWith('index.html');}
function setupCanvas(){const w=img.clientWidth;const h=img.clientHeight;if(!w||!h)return false;const dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(w*dpr));canvas.height=Math.max(1,Math.floor(h*dpr));canvas.style.width='';canvas.style.height='';if(maskEl){maskEl.style.width='';maskEl.style.height='';}
ctx=canvas.getContext('2d');ctx.setTransform(1,0,0,1,0,0);ctx.scale(dpr,dpr);paintDustLayer(w,h,dpr);cutSoftRevealWindow(w,h);return true;}
function cutSoftRevealWindow(w,h){const cx=w*0.5;const cy=h*0.44;const rOuter=Math.min(w,h)*0.22;const rInner=rOuter*0.18;const g=ctx.createRadialGradient(cx,cy,rInner,cx,cy,rOuter);g.addColorStop(0,'rgba(255,255,255,0.38)');g.addColorStop(0.22,'rgba(255,255,255,0.24)');g.addColorStop(0.48,'rgba(255,255,255,0.1)');g.addColorStop(0.72,'rgba(255,255,255,0.03)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.save();ctx.globalCompositeOperation='destination-out';ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.restore();}
function paintDustLayer(w,h,dpr){ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.fillStyle='rgba(0, 0, 0, 0.94)';ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(0, 0, 0, 0.55)';ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(0, 0, 0, 0.28)';ctx.fillRect(0,0,w,h);const bw=canvas.width;const bh=canvas.height;const id=ctx.getImageData(0,0,bw,bh);const d=id.data;const n=Math.min(4500,Math.floor(w*h*0.1));for(let i=0;i<n;i++){const ux=Math.random()*w;const uy=Math.random()*h;const x0=Math.min(bw-1,(ux*dpr)|0);const y0=Math.min(bh-1,(uy*dpr)|0);const sUser=1+Math.random()*2;const sizeDev=Math.max(1,Math.ceil(sUser*dpr));const dark=(8+Math.random()*22)|0;for(let dy=0;dy<sizeDev;dy++){const y=y0+dy;if(y>=bh)break;for(let dx=0;dx<sizeDev;dx++){const x=x0+dx;if(x>=bw)break;const j=(y*bw+x)*4;d[j]=Math.max(0,d[j]-dark);d[j+1]=Math.max(0,d[j+1]-dark);d[j+2]=Math.max(0,d[j+2]-dark);}}}
ctx.putImageData(id,0,0);}
function clearCanvasFully(){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();}
function eraseAt(clientX,clientY){if(!ctx)return;const rect=canvas.getBoundingClientRect();const x=clientX-rect.left;const y=clientY-rect.top;if(x<-BRUSH||y<-BRUSH||x>rect.width+BRUSH||y>rect.height+BRUSH)return;ctx.save();ctx.globalCompositeOperation='destination-out';if(lastX===undefined){ctx.beginPath();ctx.arc(x,y,BRUSH,0,Math.PI*2);ctx.fill();}else{ctx.lineWidth=BRUSH*2;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(lastX,lastY);ctx.lineTo(x,y);ctx.stroke();}
ctx.restore();lastX=x;lastY=y;}
function endStroke(){lastX=undefined;lastY=undefined;}
function checkRevealProgress(){if(revealed||!ctx)return;let data;try{data=ctx.getImageData(0,0,canvas.width,canvas.height).data;}catch{return;}
let cleared=0;const total=canvas.width*canvas.height;for(let i=3;i<data.length;i+=4){if(data[i]<52)cleared+=1;}
if(cleared/total<REVEAL_THRESHOLD)return;revealed=true;clearCanvasFully();textEl.textContent='Click to see!';splash.classList.add('splash--ready');bindSplashReadyHoverTilt();if(window.matchMedia('(max-width: 768px)').matches){window.setTimeout(doSplashLeave,1500);}}
function scheduleCheck(){if(rafCheck!==null)return;rafCheck=requestAnimationFrame(()=>{rafCheck=null;checkRevealProgress();});}
const TAP_MAX_MOVE_PX=14;let splashNavigated=false;let navPressActive=false;let navStartX=0;let navStartY=0;let navMoved=false;let touchNavTracking=false;let touchNavMoved=false;let touchStartX=0;let touchStartY=0;function doSplashLeave(){if(splashNavigated||!revealed)return;splashNavigated=true;sessionStorage.setItem('splash-seen','1');if(isMainPage()){splash.classList.add('is-hidden');setTimeout(()=>{restoreSplashCursorGraphic();splash.remove();},900);}else{restoreSplashCursorGraphic();window.location.href='index.html';}}
function onNavPointerDown(e){if(!revealed||e.button!==0)return;if(!splash.contains(e.target))return;navPressActive=true;navMoved=false;navStartX=e.clientX;navStartY=e.clientY;}
function onNavPointerMove(e){if(!navPressActive||!revealed)return;if((e.buttons&1)!==1)return;if(Math.hypot(e.clientX-navStartX,e.clientY-navStartY)>TAP_MAX_MOVE_PX){navMoved=true;}}
function onNavPointerUp(e){if(!navPressActive)return;navPressActive=false;if(!revealed)return;if(e.button!==0)return;if(navMoved)return;doSplashLeave();}
splash.addEventListener('mousedown',onNavPointerDown);document.addEventListener('mousemove',onNavPointerMove);document.addEventListener('mouseup',onNavPointerUp);splash.addEventListener('touchstart',(e)=>{if(!revealed||e.touches.length!==1)return;if(!splash.contains(e.target))return;touchNavTracking=true;touchNavMoved=false;const t=e.touches[0];touchStartX=t.clientX;touchStartY=t.clientY;},{passive:true});splash.addEventListener('touchmove',(e)=>{if(!touchNavTracking||!revealed)return;const t=e.touches[0];if(Math.hypot(t.clientX-touchStartX,t.clientY-touchStartY)>TAP_MAX_MOVE_PX){touchNavMoved=true;}},{passive:true});splash.addEventListener('touchend',(e)=>{if(!touchNavTracking||!revealed)return;touchNavTracking=false;if(e.touches.length>0)return;if(touchNavMoved)return;doSplashLeave();},{passive:true});splash.addEventListener('touchcancel',()=>{touchNavTracking=false;});splash.addEventListener('click',(e)=>{e.preventDefault();e.stopPropagation();});function onDocMove(e){if(!drawing||revealed)return;if(e.buttons!==1)return;eraseAt(e.clientX,e.clientY);scheduleCheck();}
function onDocUp(){if(!drawing)return;drawing=false;document.removeEventListener('mousemove',onDocMove);document.removeEventListener('mouseup',onDocUp);endStroke();checkRevealProgress();}
canvas.addEventListener('mousedown',(e)=>{if(revealed)return;e.preventDefault();drawing=true;endStroke();eraseAt(e.clientX,e.clientY);scheduleCheck();document.addEventListener('mousemove',onDocMove);document.addEventListener('mouseup',onDocUp);});canvas.addEventListener('touchstart',(e)=>{if(revealed)return;e.preventDefault();drawing=true;endStroke();const t=e.touches[0];eraseAt(t.clientX,t.clientY);scheduleCheck();},{passive:false});canvas.addEventListener('touchmove',(e)=>{if(!drawing||revealed)return;e.preventDefault();const t=e.touches[0];eraseAt(t.clientX,t.clientY);scheduleCheck();},{passive:false});canvas.addEventListener('touchend',()=>{if(!drawing)return;drawing=false;endStroke();checkRevealProgress();});canvas.addEventListener('touchcancel',()=>{drawing=false;endStroke();});function trySetup(){if(ctx)return;if(!setupCanvas())return;}
img.addEventListener('error',()=>{if(revealed)return;revealed=true;textEl.textContent='Click to see!';splash.classList.add('splash--ready');bindSplashReadyHoverTilt();if(window.matchMedia('(max-width: 768px)').matches){window.setTimeout(doSplashLeave,1500);}});img.addEventListener('load',trySetup);if(img.complete)trySetup();queueMicrotask(trySetup);requestAnimationFrame(()=>requestAnimationFrame(trySetup));}
function updateFooterMskTime(){const el=document.getElementById('footer-msk-time');if(!el)return;const now=new Date();const msk=new Date(now.toLocaleString('en-US',{timeZone:'Europe/Moscow'}));const h=msk.getHours();const m=msk.getMinutes();const s=msk.getSeconds();const ampm=h>=12?'pm':'am';const h12=h%12||12;el.textContent=[String(h12).padStart(2,'0'),String(m).padStart(2,'0'),String(s).padStart(2,'0')].join(':')+' '+ampm;}
function initFooterMskTime(){updateFooterMskTime();setInterval(updateFooterMskTime,1000);}
function activateDeferredVideo(video){const url=video.dataset.deferSrc;if(!url)return;delete video.dataset.deferSrc;video.src=url;video.load();video.play().catch(()=>{});}
function initDeferredVideos(){const nodes=document.querySelectorAll('video[data-defer-src]');if(!nodes.length)return;if(!('IntersectionObserver'in window)){nodes.forEach(activateDeferredVideo);return;}
const io=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(!entry.isIntersecting)return;const v=entry.target;io.unobserve(v);activateDeferredVideo(v);});},{rootMargin:'120px',threshold:0.01});nodes.forEach((v)=>io.observe(v));}
function initWorkFooterVideo(){document.querySelectorAll('.work-footer-video').forEach((video)=>{if(video.closest('.is-hidden'))return;video.play().catch(()=>{});});}
const PAGE_LEAVE_FALLBACK_MS=1100;let pageLeaveNavigating=false;function isInternalSiteLink(a){if(!a||a.target==='_blank'||a.hasAttribute('download'))return false;const href=a.getAttribute('href');if(!href||href==='#'||href.startsWith('#'))return false;if(/^(mailto:|tel:|javascript:)/i.test(href))return false;try{const u=new URL(a.href,window.location.href);if(u.origin!==window.location.origin)return false;const cur=new URL(window.location.href);if(u.pathname===cur.pathname&&u.search===cur.search&&u.hash)return false;return true;}catch{return false;}}
function navigateAfterPageLeave(url){if(pageLeaveNavigating)return;pageLeaveNavigating=true;document.body.classList.add('page-transition-leave');let left=false;const done=()=>{if(left)return;left=true;pageLeaveNavigating=false;window.location.href=url;};const onEnd=(e)=>{if(e.target!==document.body||e.propertyName!=='opacity')return;document.body.removeEventListener('transitionend',onEnd);done();};document.body.addEventListener('transitionend',onEnd);window.setTimeout(()=>{document.body.removeEventListener('transitionend',onEnd);done();},PAGE_LEAVE_FALLBACK_MS);}
function initPageTransitions(){if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;document.addEventListener('click',(e)=>{if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const a=e.target.closest&&e.target.closest('a[href]');if(!a||!isInternalSiteLink(a))return;e.preventDefault();navigateAfterPageLeave(a.href);});}
window.addEventListener('pageshow',(event)=>{document.body.classList.remove('page-transition-leave');pageLeaveNavigating=false;if(!event.persisted)return;document.querySelectorAll('video').forEach((v)=>{if(v.closest('.is-hidden'))return;v.play().catch(()=>{});});});function initExperimentsGalleryNoDrag(){if(!document.body.classList.contains('experiments-page'))return;const gallery=document.querySelector('.gallery');if(!gallery)return;gallery.addEventListener('dragstart',(e)=>e.preventDefault());gallery.querySelectorAll('img, video').forEach((el)=>el.setAttribute('draggable','false'));}
initPageTransitions();document.addEventListener('DOMContentLoaded',()=>{document.body.classList.remove('page-transition-leave');pageLeaveNavigating=false;initSplash();initCustomCursor();applySplashCursorGraphic();initFooterMskTime();initDeferredVideos();initWorkFooterVideo();initExperimentsGalleryNoDrag();shuffleGallery();prunePillarGalleries().then(()=>{initZinGallery();initZinGalleryMobileReveal();});});